site_name: Chuck Framework
copyright: © 2022 ebene fünf GmbH
nav:
  - index.md
theme:
    name: conia
repo_url: https://github.com/coniadev/chuck
extra:
    project: Chuck 
plugins:
    - search
    - macros:
        module_name: docs/main
markdown_extensions:
  - admonition
