name: Application Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: chuck_test
    steps:
      - name: Setup PHP extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: sqlite3, pgsql, mysql, gd, pcov, curl, xml, zip

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install packages with composer
        run: composer install

      - name: Start mysql server and create test db
        run: |
          sudo systemctl start mysql.service
          mysql -e 'CREATE DATABASE `${{ env.DB_NAME }}`;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

      - name: Start postgresql server and create test db
        run: |
          sudo systemctl start postgresql.service
          PGPASSWORD=${{ env.DB_PASSWORD }} psql -U ${{ env.DB_USER }} -d postgres -c 'CREATE DATABASE ${{ env.DB_NAME }};'

      - name: Run tests
        run: ./vendor/bin/pest
